# Build and push the image using buildx
name: Build and push container image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for Plex updates
        id: check-updates
        shell: bash
        run:  |
          sudo apt-get update
          sudo apt-get install -y jq --no-install-recommends --no-install-suggests
          ./update.sh

      - name: Set up Docker Buildx
        if: env.PLEX_UPDATED == 'true' || github.event_name != 'schedule'
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        if: env.PLEX_UPDATED == 'true' || github.event_name != 'schedule'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push
        if: env.PLEX_UPDATED == 'true' || github.event_name != 'schedule'
        uses: docker/build-push-action@v4
        id: build_push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update job summary
        shell: bash
        run: |
          echo "Image built and pushed to ghcr.io/${{ github.repository }}:latest" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.build_push.outputs.digest }}" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.build_push.outputs.metadata }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Bump version and push tag
        if: env.PLEX_UPDATED == 'true' || github.event_name != 'schedule'
        id: tag_version
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: dev

      - name: Create a GitHub release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        if: env.PLEX_UPDATED == 'true' || github.event_name != 'schedule'
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
