# Build and push the image using buildx
name: Build and push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.meta.outputs.tags }}}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}

